[package]
name = "oxscape_contour"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytemuck = {workspace = true}
num-traits = "0.2.19"
rayon = {workspace = true}
oxscape_core = {version = "0.1", path = "../oxscape_core"}
oxscape_flowmets = {version = "0.1", path = "../oxscape_flowmets", optional = true}
exn = "0.3.0"

[features]
default = ["metrics"]
metrics = ["dep:oxscape_flowmets"]

[dev-dependencies]
proptest = "1.10.0"

[lints.rust]
unused_qualifications = "warn"
missing_docs = "warn"

[lints.clippy]
pedantic = "warn"
undocumented_unsafe_blocks = "warn"
multiple_unsafe_ops_per_block = "warn"
unnecessary_safety_doc = "warn"
non_send_fields_in_send_ty = "warn"
