[package]
name = "oxscape_erode"
version = "0.1.0"
edition = "2024"

[dependencies]
exn = "0.3.0"
num-traits = "0.2.19"
oxscape_contour = {version = "0.1", path = "../oxscape_contour"}
oxscape_core = {version = "0.1", path = "../oxscape_core"}
rayon = "1.11"

[features]
fill = []
default = ["fill"]
