[package]
name = "oxscape"
version = "0.1.1"
edition.workspace = true
license.workspace = true
description = "Oxscape enables parallel flow graph (D8, Dinf) traversal in Digital Elevation Models"
readme = "README.md"
homepage = "https://codeberg.org/feefladder/oxscape/"
repository = "https://codeberg.org/feefladder/oxscape/"
keywords = ["GIS", "hydrology", "flow", "LEM", "landscape"]
categories = ["science::geo", "simulation", "concurrency"]

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
num-traits = "0.2.19"
rayon = "1.11"

[features]
default = ["metrics"]
metrics = []
